HospitalsTestsAndVaccines/Controllers/DoctorsController.cs
using HospitalsTestsAndVaccines.Models;
using HospitalsTestsAndVaccines.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Net;

using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace HospitalsTestsAndVaccines.Controllers
{
    public class DoctorsController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        public DoctorsController()
        {

        }
        

        public ActionResult Index()
        {
            var doctors = _context.Doctors.ToList();
            return View(doctors);
        }
        DateTime today = DateTime.Now.Date;

        //Details for admin
        public ActionResult Details(string id)
        {
            var viewModel = new DoctorDetailViewModel
            {
                //GetDoctor
                Doctor = _context.Doctors
                .SingleOrDefault(d => d.Id == id),

                //UpcomingAppointments = _unitOfWork.Appointments.GetTodaysAppointments(id),

                UpcomingAppointments = _context.Appointments
                .Where(d => d.Doctor.ApplicationUserId == id && d.StartDateTime >= today && d.Status == true)
                .Include(p => p.ApplicationUser)
                .OrderBy(d => d.StartDateTime)
                .ToList(),
                // GetAppointmentByDoctor
                Appointments = _context.Appointments
                .Where(p => p.ApplicationUserId == id)
                .Include(p => p.ApplicationUser)
                .Include(d => d.Doctor)
                .ToList()
            };
            return View(viewModel);
        }

        public ActionResult DoctorProfile()
        {
            var userId = User.Identity.GetUserId();
            var viewModel = new DoctorDetailViewModel
            {
                Doctor = _context.Doctors
                .SingleOrDefault(d => d.ApplicationUserId == userId),
                //UpcomingAppointments
                Appointments = _context.Appointments
                .Where(d => d.Doctor.ApplicationUserId == userId && d.StartDateTime >= today && d.Status == true)
                .Include(p => p.ApplicationUser)
                .OrderBy(d => d.StartDateTime)
                .ToList(),
            };
            return View(viewModel);
        }
        //public ActionResult Edit(string id)
        //{
        //    var doctor = _unitOfWork.Doctors.GetDoctor(id);
        //    if (doctor == null) return HttpNotFound();
        //    var viewModel = new DoctorFormViewModel()
        //    {

        //        Id = doctor.Id,
        //        Name = doctor.Name,
        //        Phone = doctor.Phone,
        //        Address = doctor.Address,
        //        IsAvailable = doctor.IsAvailable,


        //    };
        //    return View(viewModel);
        //}

        //[HttpPost]
        //public ActionResult Edit(DoctorFormViewModel viewModel)
        //{


        //    var doctorInDb = _unitOfWork.Doctors.GetDoctor(viewModel.Id);
        //    doctorInDb.Id = viewModel.Id;
        //    doctorInDb.Name = viewModel.Name;
        //    doctorInDb.Phone = viewModel.Phone;
        //    doctorInDb.Address = viewModel.Address;
        //    doctorInDb.IsAvailable = viewModel.IsAvailable;

        //    _unitOfWork.Complete();

        //    return RedirectToAction("Details", new { id = viewModel.Id });
        //}


    }

}

HospitalsTestsAndVaccines/Views/Doctors/Details.cshtml
@model HospitalsTestsAndVaccines.ViewModels.DoctorDetailViewModel
@{
    ViewBag.Title = "Profile";
}


<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Profile </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a href="@Url.Action("Edit","Doctors", new{id =Model.Doctor.Id})" class="btn-link"><i class="fa fa-edit m-right-xs"></i>Edit</a>

                    </li>
                </ul>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                    <div class="profile_img">
                        <div id="crop-avatar">
                            <!-- Current avatar -->
                            <img class="img-responsive avatar-view" src="~/Content/images/user.png" alt="Avatar" title="Change the avatar">
                        </div>
                    </div>
                    <h3>@Model.Doctor.Name</h3>
                    <ul class="list-unstyled user_data">

                        <li>
                            <i class="fa fa-map-marker user-profile-icon"></i> @Model.Doctor.Address
                        </li>
                        <li>
                            <i class="fa fa-phone"></i> @Model.Doctor.Phone
                        </li>
                    </ul>
                    <!-- start skills -->
                    @if (Model.Doctor.IsAvailable == true)
                    {
                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Available</a>
                    }
                    else
                    {
                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:red " class="badge" readonly>Closed</a>
                    }
                    <!-- end of skills -->
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Upcomming Appointments</a>
                            </li>
                            <li role="presentation" class="">
                                <a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">All</a>
                            </li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                                <!-- start patient today -->
                                <table id="patients" class="data table table-striped no-margin">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Details</th>
                                            <th></th>
                                        </tr>

                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.UpcomingAppointments)
                                        {
                                            <tr>
                                                <td>@item.ApplicationUser.FirstName</td>
                                                <td>@item.ApplicationUser.Phone</td>
                                                <td>@item.StartDateTime.ToString("MMM")-@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                                                <td>@item.StartDateTime.ToString("HH:mm")</td>
                                                <td>@item.Detail</td>
                                                <td> <a href="@Url.Action("Details","Patients", new { id = item.ApplicationUser.Id})" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                                <!-- end patient today -->
                            </div>
                            <div class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                                <table id="patients" class="data table table-striped no-margin">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Details</th>
                                            <th></th>
                                        </tr>

                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Appointments)
                                        {
                                            <tr>
                                                <td>@item.ApplicationUser.FirstName</td>
                                                <td>@item.ApplicationUser.Phone</td>
                                                <td>@item.StartDateTime.ToString("MMM")-@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                                                <td>@item.StartDateTime.ToString("HH:mm")</td>
                                                <td>@item.Detail</td>
                                                <td><a href="@Url.Action("Details","Patients", new { id = item.ApplicationUser.Id})" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function() {
            $("#patients").DataTable({
                "scrollY": "300px",
                "scrollCollapse": true,
                "paging": false,
                "filter": false,
                "info": false

            });
        });
    </script>
}

HospitalsTestsAndVaccines/Views/Doctors/DoctorProfile.cshtml
@model HospitalsTestsAndVaccines.ViewModels.DoctorDetailViewModel
@{
    ViewBag.Title = "Profile";
}


<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Profile </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a href="@Url.Action("Edit","Doctors", new{id =Model.Doctor.Id})" class="btn-link"><i class="fa fa-edit m-right-xs"></i>Edit</a>

                    </li>
                </ul>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                    <div class="profile_img">
                        <div id="crop-avatar">
                            <!-- Current avatar -->
                            <img class="img-responsive avatar-view" src="~/Content/images/user.png" alt="Avatar" title="Change the avatar">
                        </div>
                    </div>
                    <h3>@Model.Doctor.Name</h3>
                    <ul class="list-unstyled user_data">

                        <li>
                            <i class="fa fa-map-marker user-profile-icon"></i> @Model.Doctor.Address
                        </li>
                        <li>
                            <i class="fa fa-phone"></i> @Model.Doctor.Phone
                        </li>

                    </ul>
                    <!-- start skills -->
                    @if (Model.Doctor.IsAvailable == true)
                    {
                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Available</a>
                    }
                    else
                    {
                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:red " class="badge" readonly>Closed</a>
                    }
                    <!-- end of skills -->
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Appointments</a>
                            </li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                                <!-- start patient today -->
                                <table id="patients" class="data table table-striped no-margin">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Details</th>
                                            <th></th>
                                        </tr>

                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Appointments)
                                        {
                                            <tr>
                                                <td>@item.ApplicationUser.FirstName</td>
                                                <td>@item.ApplicationUser.Phone</td>
                                                <td>@item.StartDateTime.ToString("MMM")-@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                                                <td>@item.StartDateTime.ToString("HH:mm")</td>
                                                <td>@item.Detail</td>
                                                <td><a href="@Url.Action("Details","Patients", new { id = item.ApplicationUser.Id})" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>View</a></td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                                <!-- end patient today -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function() {
            $("#patients").DataTable({
                "scrollY": "300px",
                "scrollCollapse": true,
                "paging": false,
                "filter": false,
                "info": false

            });
        });
    </script>
}

HospitalsTestsAndVaccines/Views/Doctors/Index.cshtml
@model IEnumerable<HospitalsTestsAndVaccines.Core.Models.Doctor>
@{
    ViewBag.Title = "Index";
}
<div class="page-title">
    <div class="title_left">
        <h3>Doctors</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <table id="doctors" class="data table table-striped no-margin">
                    <thead>
                        <tr>
                            <th> Name </th>
                            <th>Phone </th>
                            <th>Status</th>
                            <th>Account Status</th>
                            <th><a href="@Url.Action("RegisterDoctor","Account")" class="btn btn-primary btn-xs"><i class="fa fa-edit"></i>Add</a></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @item.Name </td>
                            <td>@item.Phone</td>
                            <td>
                                @{
                                    if (item.IsAvailable == true)
                                    {
                                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Available</a>
                                    }
                                    else
                                    {
                                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:red " class="badge" readonly>Closed</a>
                                    }
                                }
                            </td>

                            <td>
                                <a href="@Url.Action("Details","Doctors", new { id = item.Id})" class="btn btn-default btn-xs"><i class="fa fa-folder"></i>Details</a>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>


</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#doctors").DataTable();
        });
    </script>
}